### ISSUE TITLE
Crash with enabled Hermes engine on React Native Android

### ISSUE THREAD

**Issue by dimaportenko** [cometchat-pro/react-native-chat-sdk#27]
The app starts crashing for release build on start if I enable Hermes engine for Android.

    com.facebook.jni.CppException: Could not get BatchedBridge, make sure your bundle is packaged correctly
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
        at android.os.Looper.loop(Looper.java:201)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37)
        at java.lang.Thread.run(Thread.java:764)
And the app is running fine if I remove the calls library from dependencies
`"@cometchat-pro/react-native-calls": "1.0.7",`

Any ideas what is the problem here?

**Comment by dimaportenko** [comment]
Support reply
`At present, CometChat doesn't have support for the Hermes engine However, I have created a feature request`

https://cometchat.canny.io/cometchat-pro-feature-requests/p/support-for-hermes-engine-in-calling-component

**Comment by proveshapyne** [comment]
Hi @dimaportenko,

I am closing this ticket as we have reached out to you via email regarding this. You will receive updates in your email when this feature is made live.

Please feel free to reach out to us if you need technical help.

Regards,
Provesha
